/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;
import java.awt.CardLayout;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

public class SignUpPanel extends javax.swing.JPanel {

    /**
     * Creates new form SignUpPanel
     */
    JPanel mainPanel;
    public SignUpPanel(JPanel mainPanel) {
        initComponents();
        this.mainPanel = mainPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtusername = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        btnSignup = new javax.swing.JButton();
        lblusername = new javax.swing.JLabel();
        txtlastname = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        lbllastname = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        lblfirstname = new javax.swing.JLabel();
        txtfirstname = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        lblpassword = new javax.swing.JLabel();
        txtpassword = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        lblphonenumber = new javax.swing.JLabel();
        txtphonenumber = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(186, 79, 84));

        txtusername.setBackground(new java.awt.Color(186, 79, 84));
        txtusername.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtusername.setForeground(new java.awt.Color(239, 234, 234));
        txtusername.setToolTipText("Username");
        txtusername.setBorder(null);

        jSeparator4.setBackground(new java.awt.Color(239, 234, 234));
        jSeparator4.setForeground(new java.awt.Color(239, 234, 234));

        btnSignup.setBackground(new java.awt.Color(186, 79, 84));
        btnSignup.setForeground(new java.awt.Color(239, 234, 234));
        btnSignup.setText("SIGN UP");
        btnSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignupActionPerformed(evt);
            }
        });

        lblusername.setBackground(new java.awt.Color(255, 255, 255));
        lblusername.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblusername.setForeground(new java.awt.Color(239, 234, 234));
        lblusername.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblusername.setText("Username:");

        txtlastname.setBackground(new java.awt.Color(186, 79, 84));
        txtlastname.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtlastname.setForeground(new java.awt.Color(239, 234, 234));
        txtlastname.setToolTipText("Username");
        txtlastname.setBorder(null);

        jSeparator5.setBackground(new java.awt.Color(239, 234, 234));
        jSeparator5.setForeground(new java.awt.Color(239, 234, 234));

        lbllastname.setBackground(new java.awt.Color(255, 255, 255));
        lbllastname.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbllastname.setForeground(new java.awt.Color(239, 234, 234));
        lbllastname.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbllastname.setText("Last Name:");

        jSeparator6.setBackground(new java.awt.Color(239, 234, 234));
        jSeparator6.setForeground(new java.awt.Color(239, 234, 234));

        lblfirstname.setBackground(new java.awt.Color(255, 255, 255));
        lblfirstname.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblfirstname.setForeground(new java.awt.Color(239, 234, 234));
        lblfirstname.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblfirstname.setText("First Name:");

        txtfirstname.setBackground(new java.awt.Color(186, 79, 84));
        txtfirstname.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtfirstname.setForeground(new java.awt.Color(239, 234, 234));
        txtfirstname.setToolTipText("Username");
        txtfirstname.setBorder(null);

        jSeparator7.setBackground(new java.awt.Color(239, 234, 234));
        jSeparator7.setForeground(new java.awt.Color(239, 234, 234));

        lblpassword.setBackground(new java.awt.Color(255, 255, 255));
        lblpassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblpassword.setForeground(new java.awt.Color(239, 234, 234));
        lblpassword.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblpassword.setText("Password:");

        txtpassword.setBackground(new java.awt.Color(186, 79, 84));
        txtpassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtpassword.setForeground(new java.awt.Color(239, 234, 234));
        txtpassword.setToolTipText("Username");
        txtpassword.setBorder(null);

        jSeparator8.setBackground(new java.awt.Color(239, 234, 234));
        jSeparator8.setForeground(new java.awt.Color(239, 234, 234));

        lblphonenumber.setBackground(new java.awt.Color(255, 255, 255));
        lblphonenumber.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblphonenumber.setForeground(new java.awt.Color(239, 234, 234));
        lblphonenumber.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblphonenumber.setText("Phone Number:");

        txtphonenumber.setBackground(new java.awt.Color(186, 79, 84));
        txtphonenumber.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtphonenumber.setForeground(new java.awt.Color(239, 234, 234));
        txtphonenumber.setToolTipText("Username");
        txtphonenumber.setBorder(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(239, 234, 234));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sign Up");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblfirstname, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(20, 20, 20)
                            .addComponent(txtfirstname, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lbllastname, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(20, 20, 20)
                            .addComponent(txtlastname, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblusername, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(20, 20, 20)
                            .addComponent(txtusername, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(20, 20, 20)
                            .addComponent(txtpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblphonenumber, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(20, 20, 20)
                            .addComponent(txtphonenumber, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(180, 180, 180)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnSignup, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 555, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblfirstname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtfirstname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(10, 10, 10)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbllastname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtlastname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(10, 10, 10)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblusername, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtusername, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(10, 10, 10)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(10, 10, 10)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblphonenumber, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtphonenumber, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(30, 30, 30)
                    .addComponent(btnSignup, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignupActionPerformed
//        try{
//            //SQL Connection
//            Class.forName("com.mysql.cj.jdbc.Driver");
//            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/digitaleducationsystem","root","monilshah");
//            //Get input data.
//            String lastname = txtlastname.getText();
//            String firstname = txtfirstname.getText();
//            String phonenumber = txtphonenumber.getText();
//            String username = txtusername.getText();
//            String password = txtpassword.getText();
//            String type = "Student";
//
//            //Query SQL -> CREATE NEW
//            String sql = "INSERT INTO LOGIN (firstname, lastname, username, password, phonenumber, TYPE) VALUES (?,?,?,?,?,?)";
//            PreparedStatement pstmt = con.prepareStatement(sql);
//            pstmt.setString(1, firstname);
//            pstmt.setString(2, lastname);
//            pstmt.setString(3, username);
//            pstmt.setString(4, password);
//            pstmt.setString(5, phonenumber);
//            pstmt.setString(6, type);
//            int affecedRows = pstmt.executeUpdate();
//            if(affecedRows > 0){
//                JOptionPane.showMessageDialog(this,"SignUp Successful");
//                StudentDashboardPanel panel = new StudentDashboardPanel(mainPanel);
//                mainPanel.add("StudentDashboardPanel",panel);
//                CardLayout layout = (CardLayout) mainPanel.getLayout();
//                layout.next(mainPanel);
//              txtlastname.setText("");
//              txtfirstname.setText("");
//              txtphonenumber.setText("");
//              txtusername.setText("");
//              txtpassword.setText("");
//            }else{
//                JOptionPane.showMessageDialog(this,"SignUp Failed");
//            }
//
//        }
//        catch(ClassNotFoundException | SQLException e){
//            System.out.println("There has been an issue while logging in");
//            System.out.println(e.getMessage());
//            JOptionPane.showMessageDialog(this, "Unable to Sign In");
//        }
                StudentDashboardPanel panel = new StudentDashboardPanel(mainPanel);
                mainPanel.add("StudentDashboardPanel",panel);
                CardLayout layout = (CardLayout) mainPanel.getLayout();
                layout.next(mainPanel);
    }//GEN-LAST:event_btnSignupActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSignup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JLabel lblfirstname;
    private javax.swing.JLabel lbllastname;
    private javax.swing.JLabel lblpassword;
    private javax.swing.JLabel lblphonenumber;
    private javax.swing.JLabel lblusername;
    private javax.swing.JTextField txtfirstname;
    private javax.swing.JTextField txtlastname;
    private javax.swing.JTextField txtpassword;
    private javax.swing.JTextField txtphonenumber;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
