/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package common;

import student.StudentDashboardPanel;
import teacher.ProfessorDashboardJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import model.User;
import model.UserDirectory;
import model.Utils;
/**
 *
 * @author Dell
 */
public class LoginPanel extends javax.swing.JPanel {

    /**
     * Creates new form LoginPanel
     */
    JPanel mainPanel;
    UserDirectory users;
    Utils utils;
    public LoginPanel(JPanel mainPanel, UserDirectory users, Utils utils) {
        initComponents();
        this.mainPanel = mainPanel;
        this.users = users;
        this.utils = utils;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        lblUnlock = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        txttype = new javax.swing.JComboBox<>();
        txtusername = new javax.swing.JTextField();
        txtpassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnSignUp = new javax.swing.JButton();

        setBackground(new java.awt.Color(186, 79, 84));

        jSeparator3.setBackground(new java.awt.Color(239, 234, 234));
        jSeparator3.setForeground(new java.awt.Color(239, 234, 234));

        jSeparator4.setBackground(new java.awt.Color(239, 234, 234));
        jSeparator4.setForeground(new java.awt.Color(239, 234, 234));

        lblUnlock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/unlock.png"))); // NOI18N

        lblUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/user.png"))); // NOI18N

        txttype.setBackground(new java.awt.Color(186, 79, 84));
        txttype.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txttype.setForeground(new java.awt.Color(239, 234, 234));
        txttype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Student", "Teacher", "Admin" }));

        txtusername.setBackground(new java.awt.Color(186, 79, 84));
        txtusername.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtusername.setForeground(new java.awt.Color(239, 234, 234));
        txtusername.setToolTipText("Username");
        txtusername.setBorder(null);

        txtpassword.setBackground(new java.awt.Color(186, 79, 84));
        txtpassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtpassword.setForeground(new java.awt.Color(239, 234, 234));
        txtpassword.setToolTipText("Password");
        txtpassword.setBorder(null);

        btnLogin.setBackground(new java.awt.Color(186, 79, 84));
        btnLogin.setForeground(new java.awt.Color(239, 234, 234));
        btnLogin.setText("LOGIN");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(239, 234, 234));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Login");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(239, 234, 234));
        jLabel8.setText("Create Account?");

        btnSignUp.setBackground(new java.awt.Color(186, 79, 84));
        btnSignUp.setForeground(new java.awt.Color(239, 234, 234));
        btnSignUp.setText("SIGN UP");
        btnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(319, 319, 319)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(btnSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblUser)
                            .addComponent(lblUnlock))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txttype, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator3)
                            .addComponent(jSeparator4)
                            .addComponent(txtpassword, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                            .addComponent(txtusername, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                            .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(313, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtpassword, txtusername});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtusername, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUser))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                        .addComponent(txtpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblUnlock)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txttype, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel8))
                    .addComponent(btnSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(82, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtpassword, txtusername});

    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        //Get input data.
        String username = txtusername.getText();
        String password = new String (txtpassword.getPassword());
        String type = txttype.getSelectedItem().toString();
        if(username.isEmpty() && password.isEmpty()){
            JOptionPane.showMessageDialog(this, "All fields are mandatory");
            return;
        }
        User user = users.containsUser(username, password, type);
        if(user != null){
            switch (type) {
                    case "Student" -> {
                        StudentDashboardPanel panel = new StudentDashboardPanel(mainPanel, users, user, utils);
                        mainPanel.add("StudentDashboardPanel",panel);
                        CardLayout layout = (CardLayout) mainPanel.getLayout();
                        layout.next(mainPanel);
                    }
                    case "Teacher" -> {
                        ProfessorDashboardJPanel panel = new ProfessorDashboardJPanel(mainPanel, user, utils);
                        mainPanel.add("ProfessorDashboardJPanel",panel);
                        CardLayout layout = (CardLayout) mainPanel.getLayout();
                        layout.next(mainPanel);
                    }
                    case "Admin" -> {
//                        AdminDashboardJPanel panel = new AdminDashboardJPanel(mainPanel);
//                        mainPanel.add("AdminDashboardJPanel",panel);
//                        CardLayout layout = (CardLayout) mainPanel.getLayout();
//                        layout.next(mainPanel);
                    }
                    default -> {
                            JOptionPane.showMessageDialog(this, "Invalid User Type");
                    }
                }
        }
        else{
            JOptionPane.showMessageDialog(null, "Username or Password in Invalid", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        //Get data from DB and check
//        try{
//            //SQL Connection
//            Class.forName("com.mysql.cj.jdbc.Driver");
//            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/digitaleducationsystem","root","monilshah");
//
//
//            //Query SQL
//            Statement stm = con.createStatement();
//            String sql = "SELECT * FROM USERS WHERE USERNAME='"+username+"' and PASSWORD='"+password+"' and TYPE='"+type+"'";
//            ResultSet rs = stm.executeQuery(sql);
//            if(rs.next()){
//                
//                switch (type) {
//                    case "Student" -> {
//                        StudentDashboardPanel panel = new StudentDashboardPanel(mainPanel);
//                        mainPanel.add("StudentDashboardPanel",panel);
//                        CardLayout layout = (CardLayout) mainPanel.getLayout();
//                        layout.next(mainPanel);
//                    }
//                    case "Teacher" -> {
//                        ProfessorDashboardJPanel panel = new ProfessorDashboardJPanel(mainPanel);
//                        mainPanel.add("ProfessorDashboardJPanel",panel);
//                        CardLayout layout = (CardLayout) mainPanel.getLayout();
//                        layout.next(mainPanel);
//                    }
//                    case "Admin" -> {
////                        AdminDashboardJPanel panel = new AdminDashboardJPanel(mainPanel);
////                        mainPanel.add("AdminDashboardJPanel",panel);
////                        CardLayout layout = (CardLayout) mainPanel.getLayout();
////                        layout.next(mainPanel);
//                    }
//                    default -> {
//                            JOptionPane.showMessageDialog(this, "Invalid User Type");
//                    }
//                }
//            }else{
//                JOptionPane.showMessageDialog(this, "Username or Password in Invalid");
//            }
//
//        }
//        catch(ClassNotFoundException | SQLException e){
//            System.out.println("There has been an issue while logging in");
//            System.out.println(e.getMessage());
//        }
//                StudentDashboardPanel panel = new StudentDashboardPanel(mainPanel);
//                mainPanel.add("StudentDashboardPanel",panel);
//                CardLayout layout = (CardLayout) mainPanel.getLayout();
//                layout.next(mainPanel);
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpActionPerformed
        SignUpPanel signUpPanel = new SignUpPanel(mainPanel, users, utils);
        mainPanel.add("SignUpPanel", signUpPanel);
        CardLayout layout = (CardLayout) mainPanel.getLayout();
        layout.next(mainPanel);
    }//GEN-LAST:event_btnSignUpActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnSignUp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lblUnlock;
    private javax.swing.JLabel lblUser;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JComboBox<String> txttype;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
