/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package teacher;

import java.awt.CardLayout;
import javax.swing.JPanel;
import model.User;
import model.Utils;

/**
 *
 * @author rachanakeshav
 */
public class ProfessorDashboardJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProfessorDashboardJPanel
     */
    JPanel mainPanel;
    User user;
    Utils utils;
    public ProfessorDashboardJPanel(JPanel mainPanel, User user, Utils utils) {
        initComponents();
        this.mainPanel= mainPanel;
        this.user = user;
        this.utils = utils;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        action1Panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblViewProfile = new javax.swing.JLabel();
        action2Panel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblCreateCourse = new javax.swing.JLabel();
        action3Panel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lblManageCourse = new javax.swing.JLabel();
        lblProfessorDashboard = new javax.swing.JLabel();

        action1Panel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 3, 3, new java.awt.Color(153, 153, 153)));
        action1Panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                action1PanelMouseClicked(evt);
            }
        });

        jLabel1.setText("jLabel1");

        lblViewProfile.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblViewProfile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblViewProfile.setText("View Profile");

        javax.swing.GroupLayout action1PanelLayout = new javax.swing.GroupLayout(action1Panel);
        action1Panel.setLayout(action1PanelLayout);
        action1PanelLayout.setHorizontalGroup(
            action1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(action1PanelLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel1))
            .addComponent(lblViewProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        action1PanelLayout.setVerticalGroup(
            action1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(action1PanelLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel1)
                .addGap(84, 84, 84)
                .addComponent(lblViewProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        action2Panel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 3, 3, new java.awt.Color(153, 153, 153)));
        action2Panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                action2PanelMouseClicked(evt);
            }
        });

        jLabel3.setText("jLabel1");

        lblCreateCourse.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblCreateCourse.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCreateCourse.setText("Create Course");

        javax.swing.GroupLayout action2PanelLayout = new javax.swing.GroupLayout(action2Panel);
        action2Panel.setLayout(action2PanelLayout);
        action2PanelLayout.setHorizontalGroup(
            action2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(action2PanelLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel3))
            .addComponent(lblCreateCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        action2PanelLayout.setVerticalGroup(
            action2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(action2PanelLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel3)
                .addGap(84, 84, 84)
                .addComponent(lblCreateCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        action3Panel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 3, 3, new java.awt.Color(153, 153, 153)));
        action3Panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                action3PanelMouseClicked(evt);
            }
        });

        jLabel5.setText("jLabel1");

        lblManageCourse.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblManageCourse.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblManageCourse.setText("Manage Course");

        javax.swing.GroupLayout action3PanelLayout = new javax.swing.GroupLayout(action3Panel);
        action3Panel.setLayout(action3PanelLayout);
        action3PanelLayout.setHorizontalGroup(
            action3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(action3PanelLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel5))
            .addComponent(lblManageCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        action3PanelLayout.setVerticalGroup(
            action3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(action3PanelLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel5)
                .addGap(84, 84, 84)
                .addComponent(lblManageCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        lblProfessorDashboard.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lblProfessorDashboard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblProfessorDashboard.setText("Professor Dashboard");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(action1Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104)
                .addComponent(action2Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addComponent(action3Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
            .addComponent(lblProfessorDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {action1Panel, action2Panel, action3Panel});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblProfessorDashboard)
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(action1Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(action2Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(action3Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(279, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {action1Panel, action2Panel, action3Panel});

    }// </editor-fold>//GEN-END:initComponents

    private void action1PanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_action1PanelMouseClicked
        // TODO add your handling code here:
        ViewProfessorProfileJPanel panel = new ViewProfessorProfileJPanel(mainPanel, user, utils);
        mainPanel.add("ViewProfessorProfileJPanel",panel);
        CardLayout layout = (CardLayout) mainPanel.getLayout();
        layout.next(mainPanel);
        
    }//GEN-LAST:event_action1PanelMouseClicked

    private void action2PanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_action2PanelMouseClicked
        // TODO add your handling code here:
        CreateCoursesJPanel panel = new CreateCoursesJPanel(mainPanel, user, utils);
        mainPanel.add("CreateCoursesJPanel",panel);
        CardLayout layout = (CardLayout) mainPanel.getLayout();
        layout.next(mainPanel);
    }//GEN-LAST:event_action2PanelMouseClicked

    private void action3PanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_action3PanelMouseClicked
        // TODO add your handling code here:
        ManageCourseJPanel panel = new ManageCourseJPanel(mainPanel, user, utils);
        mainPanel.add("ManageCourseJPanel",panel);
        CardLayout layout = (CardLayout) mainPanel.getLayout();
        layout.next(mainPanel);
    }//GEN-LAST:event_action3PanelMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel action1Panel;
    private javax.swing.JPanel action2Panel;
    private javax.swing.JPanel action3Panel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblCreateCourse;
    private javax.swing.JLabel lblManageCourse;
    private javax.swing.JLabel lblProfessorDashboard;
    private javax.swing.JLabel lblViewProfile;
    // End of variables declaration//GEN-END:variables
}
